### ISSUE TITLE
Simphonic-mayavi broken

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote-docker#41]
For unclear reasons, simphony mayavi in the latest deployment is not working. 

```
Traceback (most recent call last):
  File "/simphony/bin/mayavi2", line 7, in <module>
    from mayavi.scripts.mayavi2 import main
  File "/simphony/local/lib/python2.7/site-packages/mayavi/scripts/mayavi2.py", line 494, in <module>
    raise ImportError(msg)
ImportError: No module named pyface.tvtk_scene
```

The module is indeed completely empty, but any comparison against the production images v0.3.0 logs matches the log of the current build. Yet, it doesn't start.

This must be solved before simphony-remote 0.8.0 release

**Comment by stefanoborini** [comment]
See https://github.com/enthought/mayavi/issues/443
